-- Criação completa do banco de dados do projeto Acorda RJ.
-- Representa o estado estrutural atual do sistema, sem automação ou
-- disparo de mensagens.
--
-- USO EXCLUSIVO EM BANCO POSTGRESQL VAZIO.
-- Este arquivo falha de propósito se encontrar alguma tabela do projeto.
-- Para atualizar a estrutura, crie antes um backup completo e validado,
-- recrie um banco vazio com este arquivo e restaure somente os dados aprovados.

BEGIN;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET check_function_bodies = FALSE;
SET client_min_messages = WARNING;

DO $$
DECLARE
  objeto_existente TEXT;
BEGIN
  SELECT classe.relname
  INTO objeto_existente
  FROM pg_catalog.pg_class AS classe
  INNER JOIN pg_catalog.pg_namespace AS namespace
    ON namespace.oid = classe.relnamespace
  WHERE namespace.nspname = 'public'
    AND classe.relname IN (
      'aceites_privacidade',
      'backups_banco',
      'bairros',
      'consentimentos',
      'contatos',
      'historico_contatos',
      'importacao_linhas',
      'importacoes',
      'numeros_whatsapp',
      'modelos_mensagem',
      'campanhas',
      'comunicacoes',
      'historico_comunicacoes',
      'campanha_lotes',
      'campanha_participacoes',
      'campanha_tentativas',
      'historico_status_mensageria',
      'configuracoes_sistema',
      'historico_configuracoes_sistema',
      'eventos_webhook_mensageria',
      'sincronizacoes_limite_meta',
      'origens',
      'schema_migrations',
      'eventos',
      'historico_eventos',
      'contato_eventos',
      'solicitacoes_exclusao',
      'tentativas_login',
      'textos_formulario',
      'usuarios'
    )
  LIMIT 1;

  IF objeto_existente IS NOT NULL THEN
    RAISE EXCEPTION
      'Execução recusada: o banco já possui a estrutura do projeto (%). Este arquivo exige um banco vazio.',
      objeto_existente;
  END IF;

  IF to_regprocedure('public.atualizar_data_modificacao()') IS NOT NULL THEN
    RAISE EXCEPTION
      'Execução recusada: a função atualizar_data_modificacao já existe. Use um banco vazio.';
  END IF;
END;
$$;

CREATE FUNCTION public.atualizar_data_modificacao()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.atualizado_em = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE public.schema_migrations (
  versao VARCHAR(20) NOT NULL,
  nome_arquivo VARCHAR(255) NOT NULL,
  checksum_sha256 CHAR(64) NOT NULL,
  executada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (versao),
  CONSTRAINT schema_migrations_nome_arquivo_unico UNIQUE (nome_arquivo),
  CONSTRAINT schema_migrations_checksum_formato CHECK (
    checksum_sha256 ~ '^[a-f0-9]{64}$'
  )
);

CREATE TABLE public.bairros (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT bairros_pkey PRIMARY KEY (id),
  CONSTRAINT bairros_nome_unico UNIQUE (nome),
  CONSTRAINT bairros_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2)
);

CREATE TABLE public.origens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT origens_pkey PRIMARY KEY (id),
  CONSTRAINT origens_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT origens_slug_formato CHECK (
    slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
  ),
  CONSTRAINT origens_tipo_nao_vazio CHECK (LENGTH(TRIM(tipo)) >= 2)
);

CREATE TABLE public.usuarios (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  perfil VARCHAR(30) NOT NULL DEFAULT 'operador',
  tentativas_login_falhas INTEGER NOT NULL DEFAULT 0,
  bloqueado_ate TIMESTAMPTZ,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_email_nao_vazio CHECK (LENGTH(TRIM(email)) >= 5),
  CONSTRAINT usuarios_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT usuarios_perfil_valido CHECK (
    perfil IN ('administrador', 'operador')
  ),
  CONSTRAINT usuarios_tentativas_login_validas CHECK (
    tentativas_login_falhas >= 0
  )
);

CREATE TABLE public.eventos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  motivo TEXT NOT NULL,
  descricao TEXT,
  data_inicial TIMESTAMPTZ NOT NULL,
  data_final TIMESTAMPTZ NOT NULL,
  local_evento VARCHAR(500),
  link_evento VARCHAR(1000),
  inscricoes_inicio TIMESTAMPTZ NOT NULL,
  inscricoes_fim TIMESTAMPTZ NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'rascunho',
  criado_por_usuario_id BIGINT NOT NULL,
  atualizado_por_usuario_id BIGINT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT eventos_pkey PRIMARY KEY (id),
  CONSTRAINT eventos_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT eventos_motivo_nao_vazio CHECK (LENGTH(TRIM(motivo)) >= 2),
  CONSTRAINT eventos_periodo_valido CHECK (data_final >= data_inicial),
  CONSTRAINT eventos_periodo_inscricoes_valido CHECK (inscricoes_fim >= inscricoes_inicio),
  CONSTRAINT eventos_status_valido CHECK (
    status IN ('rascunho', 'ativo', 'encerrado', 'excluido')
  )
);

CREATE TABLE public.historico_eventos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  evento_id BIGINT NOT NULL,
  tipo_acao VARCHAR(30) NOT NULL,
  dados_anteriores JSONB,
  dados_novos JSONB,
  usuario_id BIGINT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_eventos_pkey PRIMARY KEY (id),
  CONSTRAINT historico_eventos_acao_valida CHECK (
    tipo_acao IN ('criacao', 'edicao', 'ativacao', 'encerramento', 'exclusao')
  )
);

CREATE TABLE public.contatos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150),
  telefone VARCHAR(30) NOT NULL,
  telefone_normalizado VARCHAR(20) NOT NULL,
  bairro VARCHAR(150),
  problema VARCHAR(500),
  consentimento_armazenamento BOOLEAN NOT NULL,
  consentimento_mensagens BOOLEAN NOT NULL DEFAULT FALSE,
  consentimento_armazenamento_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consentimento_mensagens_em TIMESTAMPTZ,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consentimento_tratamento_dados BOOLEAN,
  consentimento_whatsapp BOOLEAN,
  consentimento_ligacoes BOOLEAN,
  consentimentos_atualizados_em TIMESTAMPTZ,
  origem_atual VARCHAR(200),
  status_contato VARCHAR(30),
  bloqueado_para_mensagens BOOLEAN NOT NULL DEFAULT FALSE,
  origem_id BIGINT,
  idade SMALLINT,
  descricao_problema TEXT,
  bloqueado_para_ligacoes BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT contatos_pkey PRIMARY KEY (id),
  CONSTRAINT contatos_bairro_nao_vazio CHECK (
    LENGTH(TRIM(bairro)) >= 2
  ),
  CONSTRAINT contatos_consentimento_armazenamento_obrigatorio CHECK (
    consentimento_armazenamento = TRUE
  ),
  CONSTRAINT contatos_data_consentimento_mensagens CHECK (
    (consentimento_mensagens = TRUE AND consentimento_mensagens_em IS NOT NULL)
    OR
    (consentimento_mensagens = FALSE AND consentimento_mensagens_em IS NULL)
  ),
  CONSTRAINT contatos_idade_valida CHECK (
    idade IS NULL OR idade >= 0
  ),
  CONSTRAINT contatos_nome_valido CHECK (
    nome IS NULL
    OR (
      LENGTH(TRIM(nome)) >= 2
      AND TRIM(nome) ~ '[[:alpha:]]'
    )
  ),
  CONSTRAINT contatos_problema_nao_vazio CHECK (
    LENGTH(TRIM(problema)) >= 3
  ),
  CONSTRAINT contatos_telefone_nao_vazio CHECK (
    LENGTH(TRIM(telefone)) >= 8
  ),
  CONSTRAINT contatos_telefone_normalizado_apenas_numeros CHECK (
    telefone_normalizado ~ '^[0-9]+$'
  ),
  CONSTRAINT contatos_telefone_normalizado_tamanho CHECK (
    LENGTH(telefone_normalizado) BETWEEN 10 AND 15
  )
);

CREATE TABLE public.contato_eventos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  contato_id BIGINT NOT NULL,
  evento_id BIGINT NOT NULL,
  status_inscricao VARCHAR(30) NOT NULL DEFAULT 'inscrito',
  cadastrado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contato_eventos_pkey PRIMARY KEY (id),
  CONSTRAINT contato_eventos_status_valido CHECK (
    status_inscricao IN ('inscrito', 'confirmado', 'presente', 'cancelado')
  ),
  CONSTRAINT contato_eventos_contato_evento_unicos UNIQUE (contato_id, evento_id)
);

CREATE TABLE public.consentimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contato_id BIGINT,
  contato_id_original BIGINT NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  resposta BOOLEAN NOT NULL,
  texto_apresentado TEXT NOT NULL,
  versao_texto VARCHAR(100) NOT NULL,
  canal VARCHAR(50) NOT NULL,
  origem_registro VARCHAR(50) NOT NULL,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revogado_em TIMESTAMPTZ,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  estado VARCHAR(30),
  origem_id BIGINT,
  motivo_revogacao VARCHAR(500),
  registro_anterior_id BIGINT,
  CONSTRAINT consentimentos_pkey PRIMARY KEY (id),
  CONSTRAINT consentimentos_canal_valido CHECK (
    canal IN (
      'formulario_publico',
      'cadastro_manual',
      'area_administrativa',
      'importacao',
      'migracao',
      'whatsapp',
      'telefone',
      'outro'
    )
  ),
  CONSTRAINT consentimentos_estado_valido CHECK (
    estado IS NULL OR estado IN ('autorizado', 'recusado', 'revogado')
  ),
  CONSTRAINT consentimentos_motivo_revogacao_valido CHECK (
    motivo_revogacao IS NULL
    OR LENGTH(TRIM(motivo_revogacao)) BETWEEN 1 AND 500
  ),
  CONSTRAINT consentimentos_origem_registro_valida CHECK (
    origem_registro IN (
      'resposta_expressa',
      'migracao_legado',
      'revogacao',
      'atualizacao'
    )
  ),
  CONSTRAINT consentimentos_revogacao_coerente CHECK (
    ativo = FALSE OR revogado_em IS NULL
  ),
  CONSTRAINT consentimentos_tipo_valido CHECK (
    tipo IN (
      'tratamento_dados',
      'mensagens_whatsapp',
      'mensagens',
      'ligacoes'
    )
  )
);

CREATE TABLE public.solicitacoes_exclusao (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  contato_id BIGINT,
  contato_id_original BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente',
  solicitada_por_usuario_id BIGINT NOT NULL,
  analisada_por_usuario_id BIGINT,
  observacoes TEXT,
  solicitada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  analisada_em TIMESTAMPTZ,
  executada_em TIMESTAMPTZ,
  CONSTRAINT solicitacoes_exclusao_pkey PRIMARY KEY (id),
  CONSTRAINT solicitacoes_exclusao_status_valido CHECK (
    status IN ('pendente', 'aprovada', 'rejeitada')
  ),
  CONSTRAINT solicitacoes_exclusao_analise_coerente CHECK (
    (status = 'pendente' AND analisada_por_usuario_id IS NULL AND analisada_em IS NULL)
    OR
    (status IN ('aprovada', 'rejeitada') AND analisada_por_usuario_id IS NOT NULL AND analisada_em IS NOT NULL)
  ),
  CONSTRAINT solicitacoes_exclusao_execucao_coerente CHECK (
    executada_em IS NULL OR status = 'aprovada'
  )
);

CREATE TABLE public.aceites_privacidade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contato_id BIGINT NOT NULL,
  aceito BOOLEAN NOT NULL,
  texto_apresentado TEXT NOT NULL,
  versao_texto VARCHAR(100) NOT NULL,
  origem_id BIGINT NOT NULL,
  canal VARCHAR(50) NOT NULL,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT aceites_privacidade_pkey PRIMARY KEY (id),
  CONSTRAINT aceites_privacidade_aceite_obrigatorio CHECK (aceito = TRUE),
  CONSTRAINT aceites_privacidade_canal_valido CHECK (
    canal IN ('formulario_publico', 'cadastro_manual', 'outro')
  ),
  CONSTRAINT aceites_privacidade_texto_nao_vazio CHECK (
    LENGTH(TRIM(texto_apresentado)) >= 10
  )
);

CREATE TABLE public.historico_contatos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contato_id BIGINT NOT NULL,
  tipo_evento VARCHAR(50) NOT NULL,
  dados_anteriores JSONB,
  dados_novos JSONB,
  origem_id BIGINT,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_contatos_pkey PRIMARY KEY (id),
  CONSTRAINT historico_contatos_possui_dados CHECK (
    dados_anteriores IS NOT NULL OR dados_novos IS NOT NULL
  ),
  CONSTRAINT historico_contatos_tipo_evento_nao_vazio CHECK (
    LENGTH(TRIM(tipo_evento)) >= 2
  )
);

CREATE TABLE public.importacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nome_arquivo VARCHAR(255) NOT NULL,
  formato VARCHAR(10) NOT NULL,
  origem_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pre_visualizada',
  total_recebido INTEGER NOT NULL DEFAULT 0,
  relatorio JSONB,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmado_em TIMESTAMPTZ,
  CONSTRAINT importacoes_pkey PRIMARY KEY (id),
  CONSTRAINT importacoes_formato_valido CHECK (formato IN ('csv', 'xlsx', 'vcf')),
  CONSTRAINT importacoes_status_valido CHECK (
    status IN ('pre_visualizada', 'processando', 'concluida', 'falhou')
  )
);

CREATE TABLE public.importacao_linhas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  importacao_id BIGINT NOT NULL,
  numero_linha INTEGER NOT NULL,
  dados JSONB NOT NULL,
  valida BOOLEAN NOT NULL,
  erro_validacao TEXT,
  resultado VARCHAR(30) NOT NULL DEFAULT 'pendente',
  contato_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT importacao_linhas_pkey PRIMARY KEY (id),
  CONSTRAINT importacao_linhas_numero_unico UNIQUE (importacao_id, numero_linha),
  CONSTRAINT importacao_linhas_resultado_valido CHECK (
    resultado IN ('pendente','criado','complementado','ignorado','duplicado','invalido','erro')
  )
);

CREATE TABLE public.numeros_whatsapp (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  numero VARCHAR(30) NOT NULL,
  numero_normalizado VARCHAR(20) NOT NULL,
  responsavel VARCHAR(150) NOT NULL,
  observacao TEXT,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_por_usuario_id BIGINT NOT NULL,
  atualizado_por_usuario_id BIGINT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT numeros_whatsapp_nome_valido CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT numeros_whatsapp_numero_valido CHECK (numero_normalizado ~ '^[0-9]{10,15}$')
);

CREATE TABLE public.modelos_mensagem (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  texto TEXT NOT NULL,
  evento_id BIGINT,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_por_usuario_id BIGINT,
  atualizado_por_usuario_id BIGINT,
  meta_nome VARCHAR(512),
  meta_idioma VARCHAR(35),
  meta_categoria VARCHAR(50),
  meta_status VARCHAR(20) NOT NULL DEFAULT 'rascunho',
  meta_template_id VARCHAR(100),
  meta_componentes JSONB,
  meta_status_oficial VARCHAR(50),
  meta_origem VARCHAR(20) NOT NULL DEFAULT 'interno',
  meta_submetido_em TIMESTAMPTZ,
  meta_sincronizado_em TIMESTAMPTZ,
  meta_configuracao_envio JSONB NOT NULL DEFAULT '{}'::jsonb,
  excluido_em TIMESTAMPTZ,
  excluido_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT modelos_mensagem_nome_valido CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT modelos_mensagem_categoria_valida CHECK (LENGTH(TRIM(categoria)) >= 2),
  CONSTRAINT modelos_mensagem_texto_valido CHECK (LENGTH(TRIM(texto)) >= 2),
  CONSTRAINT modelos_mensagem_meta_status_valido CHECK (
    meta_status IN ('rascunho', 'em_analise', 'aprovado', 'rejeitado', 'indisponivel')
  ),
  CONSTRAINT modelos_mensagem_meta_origem_valida CHECK (meta_origem IN ('interno', 'meta')),
  CONSTRAINT modelos_mensagem_meta_componentes_objeto_valido CHECK (
    meta_componentes IS NULL OR jsonb_typeof(meta_componentes) = 'array'
  ),
  CONSTRAINT modelos_mensagem_meta_configuracao_envio_objeto_valido CHECK (
    jsonb_typeof(meta_configuracao_envio) = 'object'
  )
);

CREATE TABLE public.historico_modelos_mensagem_meta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id BIGINT NOT NULL REFERENCES public.modelos_mensagem(id),
  meta_template_id VARCHAR(100),
  acao VARCHAR(40) NOT NULL,
  status_anterior VARCHAR(50),
  status_novo VARCHAR(50),
  origem VARCHAR(30) NOT NULL,
  usuario_id BIGINT REFERENCES public.usuarios(id),
  detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_modelos_mensagem_meta_acao_valida CHECK (
    acao IN ('rascunho_criado', 'rascunho_atualizado', 'configuracao_envio',
      'submissao', 'sincronizacao', 'vinculo_inicial', 'webhook_status',
      'exclusao_logica')
  ),
  CONSTRAINT historico_modelos_mensagem_meta_origem_valida CHECK (
    origem IN ('sistema', 'api_meta', 'sincronizacao_meta', 'webhook_meta')
  ),
  CONSTRAINT historico_modelos_mensagem_meta_detalhes_validos CHECK (
    jsonb_typeof(detalhes) = 'object'
  )
);

CREATE TABLE public.campanhas (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  descricao TEXT,
  finalidade TEXT NOT NULL,
  modelo_id BIGINT,
  filtros_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'rascunho',
  responsavel_usuario_id BIGINT NOT NULL,
  pronta_em TIMESTAMPTZ,
  ativada_em TIMESTAMPTZ,
  pausada_em TIMESTAMPTZ,
  concluida_em TIMESTAMPTZ,
  cancelada_em TIMESTAMPTZ,
  arquivada_em TIMESTAMPTZ,
  arquivada_por_usuario_id BIGINT,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_por_usuario_id BIGINT NOT NULL,
  atualizado_por_usuario_id BIGINT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT campanhas_nome_valido CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT campanhas_status_valido CHECK (status IN ('rascunho','pronta','ativa','pausada','concluida','cancelada'))
);

CREATE TABLE public.comunicacoes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  contato_id BIGINT NOT NULL,
  evento_id BIGINT,
  modelo_id BIGINT,
  campanha_id BIGINT,
  numero_whatsapp_id BIGINT NOT NULL,
  operador_usuario_id BIGINT NOT NULL,
  confirmado_por_usuario_id BIGINT,
  texto_preparado TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'preparada',
  enviada_em TIMESTAMPTZ,
  respondida_em TIMESTAMPTZ,
  observacoes TEXT,
  motivo_reenvio TEXT,
  proxima_acao TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT comunicacoes_texto_valido CHECK (LENGTH(TRIM(texto_preparado)) >= 2),
  CONSTRAINT comunicacoes_status_valido CHECK (status IN (
    'nao_contatado', 'preparada', 'enviada', 'aguardando_resposta',
    'respondido', 'em_atendimento', 'concluido', 'sem_resposta',
    'nao_deseja_contato', 'recusou_atendimento', 'numero_invalido'
  )),
  CONSTRAINT comunicacoes_envio_coerente CHECK (
    status NOT IN ('enviada', 'aguardando_resposta', 'respondido', 'em_atendimento', 'concluido', 'sem_resposta')
    OR enviada_em IS NOT NULL
  )
);

CREATE TABLE public.historico_comunicacoes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  comunicacao_id BIGINT NOT NULL,
  status_anterior VARCHAR(30),
  status_novo VARCHAR(30) NOT NULL,
  usuario_id BIGINT NOT NULL,
  observacoes TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.campanha_lotes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  campanha_id BIGINT NOT NULL REFERENCES public.campanhas(id),
  tamanho_solicitado INTEGER NOT NULL,
  tamanho_efetivo INTEGER NOT NULL,
  ordem INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'reservado',
  chave_idempotencia VARCHAR(100) NOT NULL,
  criado_por_usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT campanha_lotes_tamanhos_validos CHECK (tamanho_solicitado BETWEEN 1 AND 10000 AND tamanho_efetivo BETWEEN 1 AND tamanho_solicitado),
  CONSTRAINT campanha_lotes_status_valido CHECK (status IN ('reservado','processando','processado','cancelado')),
  CONSTRAINT campanha_lotes_ordem_unica UNIQUE (campanha_id, ordem),
  CONSTRAINT campanha_lotes_idempotencia_unica UNIQUE (campanha_id, chave_idempotencia)
);

CREATE TABLE public.campanha_participacoes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  campanha_id BIGINT NOT NULL REFERENCES public.campanhas(id),
  contato_id BIGINT NOT NULL REFERENCES public.contatos(id),
  lote_original_id BIGINT NOT NULL REFERENCES public.campanha_lotes(id),
  status VARCHAR(20) NOT NULL DEFAULT 'pendente',
  reservado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT campanha_participacoes_status_valido CHECK (status IN ('pendente','enviando','enviada','entregue','lida','falhou')),
  CONSTRAINT campanha_participacao_unica UNIQUE (campanha_id, contato_id)
);

CREATE TABLE public.campanha_tentativas (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  participacao_id BIGINT NOT NULL REFERENCES public.campanha_participacoes(id),
  numero_tentativa INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente',
  identificador_externo VARCHAR(255),
  codigo_erro_externo VARCHAR(80),
  titulo_erro VARCHAR(200),
  descricao_erro TEXT,
  categoria_erro VARCHAR(100),
  permite_nova_tentativa BOOLEAN NOT NULL DEFAULT FALSE,
  resultado_indeterminado_em TIMESTAMPTZ,
  resultado_indeterminado_codigo VARCHAR(80),
  status_externo_em TIMESTAMPTZ,
  iniciada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finalizada_em TIMESTAMPTZ,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT campanha_tentativas_numero_valido CHECK (numero_tentativa > 0),
  CONSTRAINT campanha_tentativas_status_valido CHECK (status IN ('pendente','enviando','enviada','entregue','lida','falhou')),
  CONSTRAINT campanha_tentativas_resultado_indeterminado_coerente CHECK (
    resultado_indeterminado_em IS NULL
    OR (status = 'enviando' AND identificador_externo IS NULL)
  ),
  CONSTRAINT campanha_tentativas_numero_unico UNIQUE (participacao_id, numero_tentativa),
  CONSTRAINT campanha_tentativas_externo_unico UNIQUE (identificador_externo)
);

CREATE TABLE public.historico_status_mensageria (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  participacao_id BIGINT NOT NULL REFERENCES public.campanha_participacoes(id),
  tentativa_id BIGINT REFERENCES public.campanha_tentativas(id),
  status_anterior VARCHAR(20), status_novo VARCHAR(20) NOT NULL,
  origem VARCHAR(30) NOT NULL,
  codigo_erro_sanitizado VARCHAR(80), descricao_erro_sanitizada TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_status_mensageria_status_valido CHECK (status_novo IN ('pendente','enviando','enviada','entregue','lida','falhou') AND (status_anterior IS NULL OR status_anterior IN ('pendente','enviando','enviada','entregue','lida','falhou'))),
  CONSTRAINT historico_status_mensageria_origem_valida CHECK (origem IN ('reserva','processamento','webhook','reprocessamento','administrativo'))
);

CREATE TABLE public.configuracoes_sistema (
  chave VARCHAR(100) PRIMARY KEY,
  valor_inteiro INTEGER NOT NULL CHECK (valor_inteiro > 0),
  atualizado_por_usuario_id BIGINT REFERENCES public.usuarios(id),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.historico_configuracoes_sistema (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  chave VARCHAR(100) NOT NULL, valor_anterior INTEGER NOT NULL, valor_novo INTEGER NOT NULL,
  motivo TEXT NOT NULL CHECK (LENGTH(BTRIM(motivo)) >= 3),
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.eventos_webhook_mensageria (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identificador_externo VARCHAR(255) NOT NULL UNIQUE,
  tipo_evento VARCHAR(80) NOT NULL,
  processado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  identificador_mensagem VARCHAR(255),
  status_mensageria VARCHAR(20),
  status_externo_em TIMESTAMPTZ,
  dados_evento JSONB NOT NULL DEFAULT '{}'::jsonb,
  estado_processamento VARCHAR(20) NOT NULL DEFAULT 'processado',
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT eventos_webhook_estado_processamento_valido CHECK (
    estado_processamento IN ('pendente', 'processado')
  ),
  CONSTRAINT eventos_webhook_status_mensageria_valido CHECK (
    status_mensageria IS NULL OR status_mensageria IN ('enviada','entregue','lida','falhou')
  ),
  CONSTRAINT eventos_webhook_dados_evento_validos CHECK (
    jsonb_typeof(dados_evento) = 'object'
  )
);

CREATE TABLE public.sincronizacoes_limite_meta (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  limite_anterior INTEGER,
  limite_novo INTEGER,
  tier_anterior VARCHAR(40),
  tier_novo VARCHAR(40),
  origem VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL,
  codigo_erro VARCHAR(80),
  usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sincronizacoes_limite_meta_limite_anterior_valido CHECK (
    limite_anterior IS NULL OR limite_anterior > 0
  ),
  CONSTRAINT sincronizacoes_limite_meta_limite_novo_valido CHECK (
    limite_novo IS NULL OR limite_novo > 0
  ),
  CONSTRAINT sincronizacoes_limite_meta_origem_valida CHECK (
    origem IN ('consulta_api', 'webhook', 'webhook_meta')
  ),
  CONSTRAINT sincronizacoes_limite_meta_status_valido CHECK (
    status IN ('sucesso', 'falha')
  ),
  CONSTRAINT sincronizacoes_limite_meta_sucesso_valido CHECK (
    status <> 'sucesso' OR tier_novo IS NOT NULL
  )
);

CREATE INDEX sincronizacoes_limite_meta_sucesso_indice
  ON public.sincronizacoes_limite_meta (id DESC)
  WHERE status = 'sucesso';

CREATE TABLE public.tentativas_login (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  usuario_id BIGINT,
  email_informado VARCHAR(200) NOT NULL,
  endereco_ip VARCHAR(64) NOT NULL,
  agente_usuario VARCHAR(500),
  sucesso BOOLEAN NOT NULL,
  motivo VARCHAR(40) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tentativas_login_pkey PRIMARY KEY (id),
  CONSTRAINT tentativas_login_motivo_valido CHECK (
    motivo IN (
      'sucesso',
      'credenciais_invalidas',
      'usuario_inativo',
      'conta_bloqueada'
    )
  )
);

CREATE TABLE public.backups_banco (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  usuario_id BIGINT,
  status VARCHAR(20) NOT NULL DEFAULT 'processando',
  nome_arquivo VARCHAR(255),
  formato VARCHAR(20) NOT NULL DEFAULT 'sql_dados',
  versao_postgresql TEXT,
  migrations JSONB,
  tamanho_bytes BIGINT,
  sha256 CHAR(64),
  mensagem_erro VARCHAR(1000),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  concluido_em TIMESTAMPTZ,
  CONSTRAINT backups_banco_pkey PRIMARY KEY (id),
  CONSTRAINT backups_banco_status_valido CHECK (
    status IN ('processando', 'concluido', 'falhou')
  ),
  CONSTRAINT backups_banco_formato_valido CHECK (formato IN ('custom', 'sql_dados')),
  CONSTRAINT backups_banco_tamanho_valido CHECK (
    tamanho_bytes IS NULL OR tamanho_bytes >= 0
  ),
  CONSTRAINT backups_banco_sha256_valido CHECK (
    sha256 IS NULL OR sha256 ~ '^[A-F0-9]{64}$'
  ),
  CONSTRAINT backups_banco_conclusao_coerente CHECK (
    (status = 'processando' AND concluido_em IS NULL)
    OR
    (status IN ('concluido', 'falhou') AND concluido_em IS NOT NULL)
  )
);

CREATE TABLE public.textos_formulario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tipo VARCHAR(50) NOT NULL,
  versao VARCHAR(100) NOT NULL,
  texto TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT textos_formulario_pkey PRIMARY KEY (id),
  CONSTRAINT textos_formulario_texto_nao_vazio CHECK (
    LENGTH(TRIM(texto)) >= 10
  ),
  CONSTRAINT textos_formulario_tipo_valido CHECK (
    tipo IN ('aviso_privacidade', 'mensagens', 'ligacoes')
  ),
  CONSTRAINT textos_formulario_versao_nao_vazia CHECK (
    LENGTH(TRIM(versao)) >= 2
  ),
  CONSTRAINT textos_formulario_tipo_versao_unicos UNIQUE (tipo, versao)
);

CREATE UNIQUE INDEX origens_slug_unico
  ON public.origens (LOWER(slug));

CREATE UNIQUE INDEX bairros_nome_normalizado_unico
  ON public.bairros (LOWER(TRIM(nome)));

CREATE INDEX bairros_ativos_nome_indice
  ON public.bairros (LOWER(nome))
  WHERE ativo = TRUE;

CREATE UNIQUE INDEX usuarios_email_unico
  ON public.usuarios (LOWER(email));

CREATE INDEX usuarios_perfil_indice
  ON public.usuarios (perfil);

CREATE INDEX eventos_periodo_indice
  ON public.eventos (data_inicial, data_final);

CREATE INDEX historico_eventos_evento_id_indice
  ON public.historico_eventos (evento_id, criado_em DESC);

CREATE UNIQUE INDEX contatos_telefone_normalizado_unico
  ON public.contatos (telefone_normalizado);

CREATE INDEX contatos_nome_indice
  ON public.contatos (LOWER(nome));

CREATE INDEX contatos_bairro_indice
  ON public.contatos (LOWER(bairro));

CREATE INDEX contatos_problema_indice
  ON public.contatos (LOWER(problema));

CREATE INDEX contatos_criado_em_indice
  ON public.contatos (criado_em DESC);

CREATE INDEX contatos_consentimento_ligacoes_indice
  ON public.contatos (consentimento_ligacoes);

CREATE INDEX contatos_consentimento_whatsapp_indice
  ON public.contatos (consentimento_whatsapp);

CREATE INDEX contatos_origem_atual_indice
  ON public.contatos (LOWER(origem_atual));

CREATE INDEX contatos_origem_id_indice
  ON public.contatos (origem_id);

CREATE INDEX contatos_status_contato_indice
  ON public.contatos (LOWER(status_contato));

CREATE INDEX contato_eventos_evento_id_indice
  ON public.contato_eventos (evento_id, cadastrado_em DESC);

CREATE INDEX contato_eventos_contato_id_indice
  ON public.contato_eventos (contato_id);

CREATE INDEX consentimentos_contato_id_indice
  ON public.consentimentos (contato_id);

CREATE UNIQUE INDEX consentimentos_contato_tipo_ativo_unico
  ON public.consentimentos (contato_id, tipo)
  WHERE ativo = TRUE;

CREATE INDEX consentimentos_contato_original_indice
  ON public.consentimentos (contato_id_original);

CREATE INDEX consentimentos_registro_anterior_indice
  ON public.consentimentos (registro_anterior_id)
  WHERE registro_anterior_id IS NOT NULL;

CREATE UNIQUE INDEX solicitacoes_exclusao_contato_pendente_unico
  ON public.solicitacoes_exclusao (contato_id)
  WHERE status = 'pendente' AND contato_id IS NOT NULL;

CREATE INDEX solicitacoes_exclusao_status_data_indice
  ON public.solicitacoes_exclusao (status, solicitada_em DESC);

CREATE INDEX consentimentos_criado_em_indice
  ON public.consentimentos (criado_em DESC);

CREATE INDEX consentimentos_estado_indice
  ON public.consentimentos (estado);

CREATE INDEX consentimentos_origem_id_indice
  ON public.consentimentos (origem_id);

CREATE INDEX aceites_privacidade_contato_id_indice
  ON public.aceites_privacidade (contato_id);

CREATE INDEX aceites_privacidade_criado_em_indice
  ON public.aceites_privacidade (criado_em DESC);

CREATE UNIQUE INDEX aceites_privacidade_resposta_identica_unica
  ON public.aceites_privacidade (
    contato_id,
    versao_texto,
    origem_id,
    canal,
    MD5(texto_apresentado)
  )
  WHERE aceito = TRUE;

CREATE INDEX historico_contatos_contato_id_indice
  ON public.historico_contatos (contato_id);

CREATE INDEX historico_contatos_criado_em_indice
  ON public.historico_contatos (criado_em DESC);

CREATE INDEX historico_contatos_origem_id_indice
  ON public.historico_contatos (origem_id);

CREATE UNIQUE INDEX numeros_whatsapp_numero_unico ON public.numeros_whatsapp (numero_normalizado);
CREATE INDEX importacoes_criado_em_indice ON public.importacoes (criado_em DESC);
CREATE INDEX importacao_linhas_importacao_id_indice ON public.importacao_linhas (importacao_id);
CREATE INDEX importacao_linhas_contato_id_indice ON public.importacao_linhas (contato_id);
CREATE INDEX modelos_mensagem_evento_indice ON public.modelos_mensagem (evento_id, ativo);
CREATE INDEX modelos_mensagem_meta_status_indice ON public.modelos_mensagem (meta_status, ativo);
CREATE UNIQUE INDEX modelos_mensagem_meta_template_id_unico ON public.modelos_mensagem (meta_template_id) WHERE meta_template_id IS NOT NULL;
CREATE INDEX modelos_mensagem_meta_sincronizacao_indice ON public.modelos_mensagem (meta_sincronizado_em DESC) WHERE meta_template_id IS NOT NULL;
CREATE INDEX modelos_mensagem_exclusao_indice ON public.modelos_mensagem (excluido_em) WHERE excluido_em IS NULL;
CREATE INDEX historico_modelos_mensagem_meta_modelo_indice ON public.historico_modelos_mensagem_meta (modelo_id, criado_em DESC);
CREATE INDEX campanhas_ativo_nome_indice ON public.campanhas (ativo DESC, nome);
CREATE INDEX comunicacoes_contato_indice ON public.comunicacoes (contato_id, criado_em DESC);
CREATE INDEX comunicacoes_evento_indice ON public.comunicacoes (evento_id, criado_em DESC);
CREATE INDEX comunicacoes_status_indice ON public.comunicacoes (status, criado_em DESC);
CREATE INDEX comunicacoes_campanha_indice ON public.comunicacoes (campanha_id, contato_id, enviada_em DESC);
CREATE INDEX comunicacoes_modelo_indice ON public.comunicacoes (modelo_id, criado_em DESC);
CREATE INDEX comunicacoes_numero_indice ON public.comunicacoes (numero_whatsapp_id, criado_em DESC);
CREATE INDEX comunicacoes_operador_indice ON public.comunicacoes (operador_usuario_id, criado_em DESC);
CREATE INDEX historico_comunicacoes_comunicacao_indice ON public.historico_comunicacoes (comunicacao_id, criado_em DESC);
CREATE INDEX campanhas_status_indice ON public.campanhas (status, criado_em DESC);
CREATE INDEX campanhas_atualizador_indice ON public.campanhas (atualizado_por_usuario_id);
CREATE INDEX campanhas_arquivadas_indice ON public.campanhas (arquivada_em, criado_em DESC);
CREATE INDEX campanha_lotes_campanha_indice ON public.campanha_lotes (campanha_id, criado_em DESC);
CREATE INDEX campanha_participacoes_lote_indice ON public.campanha_participacoes (lote_original_id, id);
CREATE INDEX campanha_participacoes_status_indice ON public.campanha_participacoes (campanha_id, status);
CREATE INDEX campanha_participacoes_reserva_indice ON public.campanha_participacoes (reservado_em);
CREATE INDEX campanha_tentativas_status_indice ON public.campanha_tentativas (status, criado_em);
CREATE INDEX campanha_tentativas_resultado_indeterminado_indice
  ON public.campanha_tentativas (resultado_indeterminado_em)
  WHERE resultado_indeterminado_em IS NOT NULL;
CREATE INDEX historico_status_participacao_indice ON public.historico_status_mensageria (participacao_id, criado_em DESC);
CREATE INDEX eventos_webhook_mensageria_pendentes_indice
  ON public.eventos_webhook_mensageria (identificador_mensagem, id)
  WHERE estado_processamento = 'pendente';

CREATE INDEX tentativas_login_email_data_indice
  ON public.tentativas_login (LOWER(email_informado), criado_em DESC);

CREATE INDEX tentativas_login_ip_data_indice
  ON public.tentativas_login (endereco_ip, criado_em DESC);

CREATE INDEX tentativas_login_usuario_data_indice
  ON public.tentativas_login (usuario_id, criado_em DESC);

CREATE INDEX backups_banco_criado_em_indice
  ON public.backups_banco (criado_em DESC);

CREATE INDEX backups_banco_usuario_id_indice
  ON public.backups_banco (usuario_id)
  WHERE usuario_id IS NOT NULL;

CREATE UNIQUE INDEX textos_formulario_tipo_ativo_unico
  ON public.textos_formulario (tipo)
  WHERE ativo = TRUE;

CREATE TRIGGER origens_atualizar_data
BEFORE UPDATE ON public.origens
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER bairros_atualizar_data
BEFORE UPDATE ON public.bairros
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER usuarios_atualizar_data
BEFORE UPDATE ON public.usuarios
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER eventos_atualizar_data
BEFORE UPDATE ON public.eventos
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER contatos_atualizar_data
BEFORE UPDATE ON public.contatos
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER textos_formulario_atualizar_data
BEFORE UPDATE ON public.textos_formulario
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER numeros_whatsapp_atualizar_data BEFORE UPDATE ON public.numeros_whatsapp
FOR EACH ROW EXECUTE FUNCTION public.atualizar_data_modificacao();
CREATE TRIGGER modelos_mensagem_atualizar_data BEFORE UPDATE ON public.modelos_mensagem
FOR EACH ROW EXECUTE FUNCTION public.atualizar_data_modificacao();
CREATE TRIGGER campanhas_atualizar_data BEFORE UPDATE ON public.campanhas
FOR EACH ROW EXECUTE FUNCTION public.atualizar_data_modificacao();
CREATE TRIGGER comunicacoes_atualizar_data BEFORE UPDATE ON public.comunicacoes
FOR EACH ROW EXECUTE FUNCTION public.atualizar_data_modificacao();
CREATE TRIGGER campanha_lotes_atualizar_data BEFORE UPDATE ON public.campanha_lotes
FOR EACH ROW EXECUTE FUNCTION public.atualizar_data_modificacao();
CREATE TRIGGER campanha_participacoes_atualizar_data BEFORE UPDATE ON public.campanha_participacoes
FOR EACH ROW EXECUTE FUNCTION public.atualizar_data_modificacao();

ALTER TABLE public.contatos
  ADD CONSTRAINT contatos_bairro_fkey
    FOREIGN KEY (bairro) REFERENCES public.bairros(nome),
  ADD CONSTRAINT contatos_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id);

ALTER TABLE public.eventos
  ADD CONSTRAINT eventos_criado_por_usuario_id_fkey
    FOREIGN KEY (criado_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT eventos_atualizado_por_usuario_id_fkey
    FOREIGN KEY (atualizado_por_usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.historico_eventos
  ADD CONSTRAINT historico_eventos_evento_id_fkey
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id) ON DELETE CASCADE,
  ADD CONSTRAINT historico_eventos_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.contato_eventos
  ADD CONSTRAINT contato_eventos_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT contato_eventos_evento_id_fkey
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id);

ALTER TABLE public.consentimentos
  ADD CONSTRAINT consentimentos_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE SET NULL,
  ADD CONSTRAINT consentimentos_registro_anterior_id_fkey
    FOREIGN KEY (registro_anterior_id) REFERENCES public.consentimentos(id),
  ADD CONSTRAINT consentimentos_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT consentimentos_registrado_por_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.solicitacoes_exclusao
  ADD CONSTRAINT solicitacoes_exclusao_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE SET NULL,
  ADD CONSTRAINT solicitacoes_exclusao_solicitante_fkey
    FOREIGN KEY (solicitada_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT solicitacoes_exclusao_analista_fkey
    FOREIGN KEY (analisada_por_usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.aceites_privacidade
  ADD CONSTRAINT aceites_privacidade_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT aceites_privacidade_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT aceites_privacidade_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.historico_contatos
  ADD CONSTRAINT historico_contatos_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT historico_contatos_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT historico_contatos_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.numeros_whatsapp
  ADD CONSTRAINT numeros_whatsapp_criador_fkey
    FOREIGN KEY (criado_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT numeros_whatsapp_atualizador_fkey
    FOREIGN KEY (atualizado_por_usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.importacoes
  ADD CONSTRAINT importacoes_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT importacoes_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.importacao_linhas
  ADD CONSTRAINT importacao_linhas_importacao_id_fkey
    FOREIGN KEY (importacao_id) REFERENCES public.importacoes(id) ON DELETE CASCADE,
  ADD CONSTRAINT importacao_linhas_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE SET NULL;

ALTER TABLE public.modelos_mensagem
  ADD CONSTRAINT modelos_mensagem_evento_fkey
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id) ON DELETE SET NULL,
  ADD CONSTRAINT modelos_mensagem_criador_fkey
    FOREIGN KEY (criado_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT modelos_mensagem_atualizador_fkey
    FOREIGN KEY (atualizado_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT modelos_mensagem_excluidor_fkey
    FOREIGN KEY (excluido_por_usuario_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;

ALTER TABLE public.comunicacoes
  ADD CONSTRAINT comunicacoes_contato_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT comunicacoes_evento_fkey
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id) ON DELETE SET NULL,
  ADD CONSTRAINT comunicacoes_modelo_fkey
    FOREIGN KEY (modelo_id) REFERENCES public.modelos_mensagem(id) ON DELETE SET NULL,
  ADD CONSTRAINT comunicacoes_campanha_fkey
    FOREIGN KEY (campanha_id) REFERENCES public.campanhas(id) ON DELETE SET NULL,
  ADD CONSTRAINT comunicacoes_numero_fkey
    FOREIGN KEY (numero_whatsapp_id) REFERENCES public.numeros_whatsapp(id),
  ADD CONSTRAINT comunicacoes_operador_fkey
    FOREIGN KEY (operador_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT comunicacoes_confirmador_fkey
    FOREIGN KEY (confirmado_por_usuario_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;

ALTER TABLE public.campanhas
  ADD CONSTRAINT campanhas_criador_fkey
    FOREIGN KEY (criado_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT campanhas_atualizador_fkey
    FOREIGN KEY (atualizado_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT campanhas_arquivador_fkey
    FOREIGN KEY (arquivada_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT campanhas_modelo_novo_fkey
    FOREIGN KEY (modelo_id) REFERENCES public.modelos_mensagem(id),
  ADD CONSTRAINT campanhas_responsavel_novo_fkey
    FOREIGN KEY (responsavel_usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.historico_comunicacoes
  ADD CONSTRAINT historico_comunicacoes_comunicacao_fkey
    FOREIGN KEY (comunicacao_id) REFERENCES public.comunicacoes(id) ON DELETE CASCADE,
  ADD CONSTRAINT historico_comunicacoes_usuario_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.tentativas_login
  ADD CONSTRAINT tentativas_login_usuario_id_fkey
    FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.backups_banco
  ADD CONSTRAINT backups_banco_usuario_id_fkey
    FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

COMMENT ON TABLE public.contatos IS
  'Pessoas cadastradas por meio do formulário público.';

COMMENT ON COLUMN public.contatos.telefone IS
  'Telefone no formato visual oficial do sistema.';

COMMENT ON COLUMN public.contatos.telefone_normalizado IS
  'Telefone contendo somente números, utilizado para impedir duplicidade.';

COMMENT ON COLUMN public.contatos.problema IS
  'Categoria do problema. A coluna foi preservada por compatibilidade.';

COMMENT ON COLUMN public.contatos.consentimento_armazenamento IS
  'Indica autorização para armazenamento dos dados. Deve ser verdadeiro para existir cadastro.';

COMMENT ON COLUMN public.contatos.consentimento_mensagens IS
  'Indica se a pessoa autorizou mensagens futuras.';

COMMENT ON COLUMN public.contatos.consentimento_armazenamento_em IS
  'Data e hora em que o consentimento para armazenamento foi registrado.';

COMMENT ON COLUMN public.contatos.consentimento_mensagens_em IS
  'Data e hora da autorização para mensagens futuras. Fica nulo quando não autorizado.';

COMMENT ON COLUMN public.contatos.idade IS
  'Idade informada no cadastro. Registros legados permanecem NULL.';

COMMENT ON COLUMN public.contatos.descricao_problema IS
  'Descrição opcional complementar à categoria do problema.';

COMMENT ON TABLE public.usuarios IS
  'Usuários internos autorizados a acessar o painel administrativo.';

COMMENT ON TABLE public.bairros IS
  'Catálogo oficial dos bairros do município do Rio de Janeiro usado por todos os cadastros.';

COMMENT ON COLUMN public.contatos.bairro IS
  'Nome canônico validado pelo catálogo public.bairros.';

COMMENT ON COLUMN public.usuarios.senha_hash IS
  'Hash da senha gerado pela aplicação com bcrypt. Nunca armazenar senha em texto puro.';

-- Configurações técnicas necessárias para o backend operar em um banco novo.
-- Não há dados pessoais nestes registros.
-- Fonte: camada Limite de Bairros da Prefeitura da Cidade do Rio de Janeiro,
-- acrescida do bairro Argentino, criado pela Lei Municipal nº 8.020/2025.
INSERT INTO public.bairros (nome)
VALUES
  ('Abolição'),
  ('Acari'),
  ('Água Santa'),
  ('Alto da Boa Vista'),
  ('Anchieta'),
  ('Andaraí'),
  ('Anil'),
  ('Argentino'),
  ('Bancários'),
  ('Bangu'),
  ('Barra da Tijuca'),
  ('Barra de Guaratiba'),
  ('Barra Olímpica'),
  ('Barros Filho'),
  ('Benfica'),
  ('Bento Ribeiro'),
  ('Bonsucesso'),
  ('Botafogo'),
  ('Brás de Pina'),
  ('Cachambi'),
  ('Cacuia'),
  ('Caju'),
  ('Camorim'),
  ('Campinho'),
  ('Campo dos Afonsos'),
  ('Campo Grande'),
  ('Cascadura'),
  ('Catete'),
  ('Catumbi'),
  ('Cavalcanti'),
  ('Centro'),
  ('Cidade de Deus'),
  ('Cidade Nova'),
  ('Cidade Universitária'),
  ('Cocotá'),
  ('Coelho Neto'),
  ('Colégio'),
  ('Complexo do Alemão'),
  ('Copacabana'),
  ('Cordovil'),
  ('Cosme Velho'),
  ('Cosmos'),
  ('Costa Barros'),
  ('Curicica'),
  ('Del Castilho'),
  ('Deodoro'),
  ('Encantado'),
  ('Engenheiro Leal'),
  ('Engenho da Rainha'),
  ('Engenho de Dentro'),
  ('Engenho Novo'),
  ('Estácio'),
  ('Flamengo'),
  ('Freguesia (Ilha)'),
  ('Freguesia (Jacarepaguá)'),
  ('Galeão'),
  ('Gamboa'),
  ('Gardênia Azul'),
  ('Gávea'),
  ('Gericinó'),
  ('Glória'),
  ('Grajaú'),
  ('Grumari'),
  ('Guadalupe'),
  ('Guaratiba'),
  ('Higienópolis'),
  ('Honório Gurgel'),
  ('Humaitá'),
  ('Ilha de Guaratiba'),
  ('Inhaúma'),
  ('Inhoaíba'),
  ('Ipanema'),
  ('Irajá'),
  ('Itanhangá'),
  ('Jabour'),
  ('Jacaré'),
  ('Jacarepaguá'),
  ('Jacarezinho'),
  ('Jardim América'),
  ('Jardim Botânico'),
  ('Jardim Carioca'),
  ('Jardim Guanabara'),
  ('Jardim Sulacap'),
  ('Joá'),
  ('Lagoa'),
  ('Lapa'),
  ('Laranjeiras'),
  ('Leblon'),
  ('Leme'),
  ('Lins de Vasconcelos'),
  ('Madureira'),
  ('Magalhães Bastos'),
  ('Mangueira'),
  ('Manguinhos'),
  ('Maracanã'),
  ('Maré'),
  ('Marechal Hermes'),
  ('Maria da Graça'),
  ('Méier'),
  ('Moneró'),
  ('Olaria'),
  ('Osvaldo Cruz'),
  ('Paciência'),
  ('Padre Miguel'),
  ('Paquetá'),
  ('Parada de Lucas'),
  ('Parque Anchieta'),
  ('Parque Colúmbia'),
  ('Pavuna'),
  ('Pechincha'),
  ('Pedra de Guaratiba'),
  ('Penha'),
  ('Penha Circular'),
  ('Piedade'),
  ('Pilares'),
  ('Pitangueiras'),
  ('Portuguesa'),
  ('Praça da Bandeira'),
  ('Praça Seca'),
  ('Praia da Bandeira'),
  ('Quintino Bocaiúva'),
  ('Ramos'),
  ('Realengo'),
  ('Recreio dos Bandeirantes'),
  ('Riachuelo'),
  ('Ribeira'),
  ('Ricardo de Albuquerque'),
  ('Rio Comprido'),
  ('Rocha'),
  ('Rocha Miranda'),
  ('Rocinha'),
  ('Sampaio'),
  ('Santa Cruz'),
  ('Santa Teresa'),
  ('Santíssimo'),
  ('Santo Cristo'),
  ('São Conrado'),
  ('São Cristóvão'),
  ('São Francisco Xavier'),
  ('Saúde'),
  ('Senador Camará'),
  ('Senador Vasconcelos'),
  ('Sepetiba'),
  ('Tanque'),
  ('Taquara'),
  ('Tauá'),
  ('Tijuca'),
  ('Todos os Santos'),
  ('Tomás Coelho'),
  ('Turiaçú'),
  ('Urca'),
  ('Vargem Grande'),
  ('Vargem Pequena'),
  ('Vasco da Gama'),
  ('Vaz Lobo'),
  ('Vicente de Carvalho'),
  ('Vidigal'),
  ('Vigário Geral'),
  ('Vila da Penha'),
  ('Vila Isabel'),
  ('Vila Kennedy'),
  ('Vila Kosmos'),
  ('Vila Militar'),
  ('Vila Valqueire'),
  ('Vista Alegre'),
  ('Zumbi');

INSERT INTO public.origens (nome, slug, tipo, ativa)
VALUES
  ('Formulário público', 'formulario-publico', 'formulario', TRUE),
  ('Cadastro manual', 'cadastro-manual', 'manual', TRUE);

INSERT INTO public.configuracoes_sistema (chave, valor_inteiro)
VALUES ('limite_mensagens_24h', 250);

INSERT INTO public.textos_formulario (tipo, versao, texto)
VALUES
  (
    'aviso_privacidade',
    'aviso_privacidade_v4',
    'Li o Aviso de Privacidade e consinto com o tratamento dos dados necessários para minha participação voluntária no projeto Acorda RJ.'
  ),
  (
    'mensagens',
    'mensagens_whatsapp_v3',
    'Autorizo o recebimento de mensagens pelo WhatsApp enviadas pelo projeto Acorda RJ e por Diogo Ventura, incluindo informações sobre ações sociais, projetos comunitários, pesquisas, eventos e conteúdos políticos. Posso revogar esta autorização a qualquer momento pelo canal indicado na Política de Privacidade.'
  ),
  (
    'ligacoes',
    'ligacoes_v3',
    'Autorizo o recebimento de ligações telefônicas relacionadas às ações e iniciativas do projeto Acorda RJ. Posso revogar esta autorização a qualquer momento pelo canal indicado na Política de Privacidade.'
  );

INSERT INTO public.schema_migrations (
  versao,
  nome_arquivo,
  checksum_sha256
) VALUES
  ('001', '001_validar_estrutura_atual.sql', '7aef945e473bce835222ccdb4df9c792151872becaf0d2313e6de35fe781e136'),
  ('002', '002_normalizar_nomes_importados.sql', 'a62f33a5a53c6d931f9f58e3aff2864170669f0f750fb8084dd9a7ba5ba680eb'),
  ('003', '003_garantir_eventos_participantes.sql', '266712d2a762b159ce4805495825b6e39ca51d727ef3ceccf3054433dd97d8a6'),
  ('004', '004_permitir_varios_eventos_ativos.sql', '7bea0fb8ad8385e6167543846991cba81d508c9f6c8de053d774c0fdb3a3dc35'),
  ('005', '005_padronizar_telefones_contatos.sql', 'e4a97142a38ba42b5de283a9aeb0e72ca0107acc2d3e394cba083b0a72b12977'),
  ('006', '006_criar_campanhas_lotes_mensageria.sql', '1f05f7e554233eadf8efebce26e89476392dc33440e001ce24379a31f1fc40a1'),
  ('007', '007_adicionar_triggers_campanhas.sql', 'aa26f0557f23ec757577e38e6a79c3ad6ed0071143b67fd8d3b4deb35336e2b6'),
  ('008', '008_permitir_backup_sql_dados.sql', '0adcd0770538a7ce9a90edf3e9d325b9eb7a6d4faf9058c94eb02c6fd07be51d'),
  ('009', '009_integrar_meta_cloud_api.sql', '8187b63d67bfcd575e3c62c2feb5ee144a585118ba450b961312176e4d520fa5'),
  ('010', '010_permitir_importacao_vcf.sql', '7f5d4dff3bf9f62d55868e12a436f350b9a2c1d073a7e8c64c48fe01d6657c5c'),
  ('011', '011_sincronizar_limite_meta.sql', '137c3b4334f0a50e9d851a120074e94ecd2a681e0269caf583c193e58f7cddf6'),
  ('012', '012_identificar_webhook_meta.sql', '18a4295ae9d64f636a34ad7f239f3ee637e6cda1287b2e01faf04c1400adbc0a'),
  ('013', '013_gerenciar_templates_oficiais_meta.sql', 'a1a455aa7a0438d2e5b2dbbafeb6b2cb256b47a080d9974689a3c097e33d9dc6'),
  ('014', '014_garantir_auditoria_campanhas.sql', 'e856eec3eda0d280534e996e60dad3e2c3d3aa11b95b41f791d0d5d6d36e6f30'),
  ('015', '015_atualizar_templates_por_webhook_meta.sql', 'a7942ed6fbc44d230200ffca95baffa1626bbf089cca5081fff6f4a030596b9d'),
  ('016', '016_alinhar_status_campanhas.sql', '0a9ae25dce9417295dc249e284fbe7f9b2584488887c095d0405068ab6a85b3d'),
  ('017', '017_arquivar_campanhas_com_historico.sql', 'c0f9c7f3fd353b8277ba199cf113c6654ed741ae95421b44223205fed14af654'),
  ('018', '018_garantir_telefone_canonico_unico.sql', '782bf9795daa02bbdd7e30a9efaabd7888977447efed1a4cc99327ba3af5cff2'),
  ('019', '019_remover_limite_etario_cadastros.sql', 'fa99c9555c259385314b9d38fe35ac2426ae3782b593cf0228b27598b42348b9'),
  ('020', '020_excluir_modelos_sem_apagar_historico.sql', '456f3bae47329d573d9b7b0c9858578f23863f71f11106fdeebc99955ae3b70b'),
  ('021', '021_resiliencia_envio_webhook.sql', '89c194e0f41429fc904f55bac66c259155346d1e5dc470c6d3d2f5e25b849069'),
  ('022', '022_metadados_backup_completo.sql', '6a41e1edf30183d8d7605d737e30b68e2ce1efb4e1af70bef0b19f5cdbef0ba8');

-- Controle de recuperação: nunca incluir no dump operacional ou no pg_restore.
CREATE SCHEMA IF NOT EXISTS recuperacao;
REVOKE ALL ON SCHEMA recuperacao FROM PUBLIC;
CREATE TABLE recuperacao.estado (
  id BOOLEAN PRIMARY KEY DEFAULT true CHECK (id),
  manutencao BOOLEAN NOT NULL DEFAULT false,
  auth_epoch BIGINT NOT NULL DEFAULT 0,
  operacao_id UUID,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO recuperacao.estado(id) VALUES (true);
CREATE TABLE recuperacao.operacoes (
  id UUID PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  fase TEXT NOT NULL,
  dados JSONB NOT NULL DEFAULT '{}',
  erro TEXT
);
CREATE TABLE recuperacao.auditoria (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  operacao_id UUID,
  usuario_id BIGINT,
  evento TEXT NOT NULL,
  dados JSONB NOT NULL DEFAULT '{}',
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Comprovantes de admissão. Uma execução sem término nunca expira por idade.
CREATE TABLE recuperacao.admissoes (
  id UUID PRIMARY KEY,
  tipo TEXT NOT NULL,
  iniciado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  concluido_em TIMESTAMPTZ
);
CREATE INDEX admissoes_abertas ON recuperacao.admissoes(iniciado_em) WHERE concluido_em IS NULL;
CREATE TABLE recuperacao.webhooks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  chave CHAR(64) NOT NULL UNIQUE,
  payload JSONB NOT NULL,
  tipo TEXT NOT NULL,
  requer_meta BOOLEAN NOT NULL,
  aplicado_em TIMESTAMPTZ,
  erro TEXT,
  recebido_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX webhooks_pendentes ON recuperacao.webhooks(id) WHERE aplicado_em IS NULL;
-- Sem FK, trigger ou view apontando para o conjunto operacional.
ALTER TABLE public.backups_banco ADD COLUMN manifesto JSONB;
INSERT INTO public.schema_migrations(versao,nome_arquivo,checksum_sha256)
VALUES ('023','023_controle_recuperacao.sql','2785a8f3d41067bd478050d87adf868d05e4850f4ec058b15f7307b9f5053be3');

COMMIT;
